- name: Add Nomad repository RedHat
  command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: "ansible_os_family == 'RedHat'"

- name: Add Docker repository RedHat
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: "ansible_os_family == 'RedHat'"