- name: "Install required packages on RedHat"
  yum:
    pkg: "{{ item }}"
    state: latest
  when: "ansible_os_family == 'RedHat'"
  with_items:
    - unzip
    - gzip
    - yum-utils
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - epel-release
    - wget

- name: "Install PIP"
  yum:
    pkg: "{{ item }}"
    state: latest
  when: "ansible_os_family == 'RedHat'"
  with_items:
    - python-pip
    - python-setuptools

- pip:
    name: python-nomad

# - name: "Install required packages on Debian"
#   apt:
#     pkg: "{{ item }}" 
#     state: latest
#   when: "ansible_os_family == 'Debian'"
#   with_items:
#     - unzip
#     - gzip
#     - yum-utils